### ISSUE TITLE
Identify feasability of creating gold standard for date format in the 2014 i2b2 dataset

### ISSUE THREAD

**Issue by tschaffter** [data2health/nlp-sandbox#59]
## Motivation

Benchmark the ability of Date Annotators to identify the format of a date string (ISO 8601)

## Tasks

- [x] Compile some stats about date occurrences in the training and evaluation set of the i2b2 dataset
- [x] Evaluate the rate at which we could manually annotate the date format
- [ ] Create 2-3 slides that describes a protocol to annotate the date format

**Comment by tschaffter** [comment]
## Information about the DATE annotations

- The evaluation set has 4980 date annotations from 514 notes (100%)
- The training set has 7495 date annotations from 790 notes (100%)

Total: 12475 date annotations

## ISO  8601 and beyond

[Momentjs](https://momentjs.com/docs/#/parsing/string/)

> When creating a moment from a string, we first check if the string matches known ISO 8601 formats, we then check if the string matches the RFC 2822 Date time format before dropping to the fall back of new Date(string) if a known format is not found.

[List of format](https://momentjscom.readthedocs.io/en/latest/moment/04-displaying/01-format/)

**Comment by tschaffter** [comment]
## Update

- I've identified that we can annotate the date format. Will move forward with the annotation.
