### ISSUE TITLE
Prepare codebase for evaluator

### ISSUE THREAD

**Issue by tschaffter** [data2health/nlp-sandbox#60]
## Motivation

Create a python program that evaluates the performance of an NLP Tool.

## Background

For the NLP Tasks considered (annotation tasks), we will use the same performance metrics as in the 2014 i2b2 NLP de-identification challenge. These metrics are Precision, Recall and F1 computed for different evaluation cases (e.g. instances, tokens, accepting that the last character is wrong)

The starting code base is available in the GH repo below. This fork contains the scripts used during the 2014 challenge to evaluate the performance of the submission. The fork updates this code so that it runs with python 3.x.

https://github.com/tschaffter/i2b2_evaluation_scripts

An issue with the current implementation is that it's not modular and difficult to read and extend, thus making it harder to debug than it should.

## Task

- [ ] Create the command-line interface to better understand the options that should be provided to the script
- [ ] Create a few input and output files in JSON format from the XML files of the i2b2 dataset to use as test files during the development of the evaluation script
- [ ] Once ready, package the evaluation script in a Docker image
- [ ] Create a GH workflow to publish the Docker image to DockerHub
