### ISSUE TITLE
Create initial codebase of the date annotator example

### ISSUE THREAD

**Issue by tschaffter** [data2health/nlp-sandbox#61]
## Motivation

- Provide an example implementation of a date annotator to users of the NLP Sandbox
- Have an implementation handy that we can use during the development of the submission infrastructure

## Task

- [x] Create the GH repo that will include the codebase (https://github.com/data2health/nlp-sandbox-date-annotator-example)
- [x] Populate the repo with an initial implementation in python generated by openapi-generator
- [Create a README that describes
  - [ ] how the initial code base has been generated
  - [ ] how to update the codebase when a new OpenAPI specification has changed
  - [ ] how to start the date annotator server manually
  - [ ] how to deploy the annotator using Docker
- [x] Create a Docker image that starts the Date Annotator service

## Notes

- Consider creating a GH repo template for the implementation of new NLP Tasks based on an OpenAPI specification provided by the NLP Sandbox

**Comment by tschaffter** [comment]
## Update

- We have an early version of a [date annotator service](https://github.com/data2health/nlp-sandbox-date-annotator-example)
- I will take care of writing the doc for this first service

**Comment by tschaffter** [comment]
An example implementation of the date annotation service is available here:
https://github.com/data2health/nlp-sandbox-date-annotator-example

There are still improvements that we can make but those are tracked in the above GH repo.
