### ISSUE TITLE
Create slides that describes the three designs considered for submission infrastructure

### ISSUE THREAD

**Issue by tschaffter** [data2health/nlp-sandbox#62]
## Motivation

Communicate efficiently to strengths and weaknesses of each designs

## Task

- [ ] Create slides that describes the Design 1
- [ ] Create slides that describes the Design 2
- [ ] Create slides that describes the Design 3
