### ISSUE TITLE
Review n2c2 2014 Challenge

### ISSUE THREAD

**Issue by tschaffter** [data2health/nlp-sandbox#7]
https://portal.dbmi.hms.harvard.edu/projects/n2c2-2014/

## Tasks

- [x] Identify the goal(s) of the challenge
- [x] Identify the scoring metrics applied
- Datasets
  - [x] Get a copy of the dataset files
  - [x] Review the content of the dataset (number of files, etc.)
- Submissions
  - [ ] Retrieve the submissions (may need to ask the organizers directly)
  - [x] Review the participation to the challenge (number of teams, number of submission, etc.)

**Comment by yy6linda** [comment]
**2014 i2b2 challenge:**

**The goal(s) of the challenge**
de-identification for clinical notes

**Submission**
For this challenge, there are two types of submission:
1.System output
2.Software: assessed by its useability(Evaluation of submitted software will be evaluated by the program committee on factors such as ease of installation and ease of use.)

**Evaluation** precision recall F1(scripts in i2b2_evaluation_scripts-master)
 
**Datasets**
 Get a copy of the dataset files(https://portal.dbmi.hms.harvard.edu/projects/n2c2-nlp/)
Training _gold1: 521
Training_gold2: 269
testing : 514
 Review the content of the dataset (number of files, etc.)

**Submissions**
 Retrieve the submissions (may need to ask the organizers directly)
 Review the participation to the challenge (number of teams, number of submission, etc.)  28

**Comment by tschaffter** [comment]
@yy6linda Are the submissions publicly available?

**Comment by yy6linda** [comment]
Yes, every participant submitted a paper to summarize their models but code is not usually available.

**Comment by tschaffter** [comment]
Is the list of papers available somewhere? If yes can put copy/paste the link to this page here?

**Comment by yy6linda** [comment]
Access to the paper will be granted when access to data is approved. https://portal.dbmi.hms.harvard.edu/projects/n2c2-nlp/
